### ISSUE TITLE
Issues in Lubuntu 22.04 VM

### ISSUE THREAD

**Issue by stefonarch** [severusseptimius/lxqt-1.1-debian#1]
After an `apt-get update` and removing libfm-qt* I get
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqtermwidget5-1-dev : Depends: libqtermwidget5-1 (= 1.1.0-1) but it is not installable
 lxqt-runner : Depends: libmuparser2v5 (>= 2.3.3) but 2.2.6.1+dfsg-1build1 is to be installed
 qterminal : Depends: libqtermwidget5-1 (>= 1.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
``` 
I removed those packages, so it finihed install,  but at the end:
` N: Download is performed unsandboxed as root as file '/home/stef/lxqt-1.1-debian/lxqt/libfm-qt-l10n_1.1.0-1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`

It looks like the libfm-qt* removal removed also openbox, no WM list art reboot.

EDIT: no, openbox was still installed.

The libfm-qt* removal removed also the lubuntu styling. Should test again without that.

**Comment by severusseptimius** [comment]
I see... 
It's my fault that hadn't noticed these problems because I instaled them on an ubuntu server machine, and thus the lubuntu styling was never there + I like to use xfwm, not openbox.
I am making a PPA for Ubuntu that *should resolve the problems*.

About this,  `libqtermwidget5-1-dev : Depends: libqtermwidget5-1 (= 1.1.0-1) but it is not installable`, I have now see I have forgot to upload this package: `libqtermwidget5-1`. Thanks. 

About the other conflicts, I just assumed the normal course of action would be to `apt --fix-broken install`. I have updated the README file.


> I removed those packages, so it finihed install, but at the end:
> N: Download is performed unsandboxed as root as file '/home/stef/lxqt-1.1-debian/lxqt/libfm-qt-l10n_1.1.0-1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

About this, I have never seen such a warning while installing on 3 different computers. Again, the PPA should solve all these issues.

**Comment by stefonarch** [comment]
Thanks to you! I'll retest it, without removing nothing, also on a genuine debian bullseye VM, installing now.

**Comment by severusseptimius** [comment]
Even if you remove nothing, there will still be conflicts that would be solved with `apt --fix-broken install`.
A big part of this problem is that debian/ubuntu uuses the soname in the package name (for example, libfm-qt8=libfm-qt version 0.16, and libfm-qt11=libfm-qt11).

**Comment by severusseptimius** [comment]
Also, unless you really need them, you shouldn't install the -dbgsym packages. They increase the memory usage and do basically nothing

**Comment by iamthesenate1** [comment]
Here is the PPA:
https://launchpad.net/~severusseptimius/+archive/ubuntu/lxqt

I haven't tested it yet. I will do it tomorrow.

**Comment by severusseptimius** [comment]
Here is the PPA:
https://launchpad.net/~severusseptimius/+archive/ubuntu/lxqt

I haven't tested it yet. I will do it tomorrow.

**Comment by stefonarch** [comment]
> Here is the PPA: https://launchpad.net/~severusseptimius/+archive/ubuntu/lxqt
> 
> I haven't tested it yet. I will do it tomorrow.

I did in WM with a fresh installation of 22.04: it works flawlessly, kudos!

**Comment by severusseptimius** [comment]
Thanks for testing! 
I have updated the README file, recommending the PPA.
