### ISSUE TITLE
System tray icon just blank with square black color and misplace.

### ISSUE THREAD

**Issue by lidgnulinux** [severusseptimius/lxqt-1.1-debian#3]
- First, I need to thank you for bringing LXQT 1.1.0 to debian.
- Second, I'm getting issue with lxqt-powermanagement (it doesn't show me the icon / icon is missing). I already set it to use icon theme and sure my icon theme has battery icon on it.
- I'm on debian sid.

**Comment by lidgnulinux** [comment]
UPDATE: lxqt-powermanagement is fine when I use it outside lxqt DE (I use it on dwl + waybar, the icon shows). I suspect tray widget is mess up or something.

**Comment by lidgnulinux** [comment]
Update, Finally figure it out where is icon tray go. It seems misplace and just a blank with black color. here is an example for lxqt-powermanagement icon (top-left screen).
![tray-icon-](https://user-images.githubusercontent.com/99301306/164682563-b0b0c9d2-4896-4ae6-aee4-faa87713a8cd.jpg)

**Comment by severusseptimius** [comment]
I recommendthat you do `sudo apt purge lxqt-panel* lxqt-powermanagement*`. This will eliminate any suspicion that the problem is caused by bad config files.

If you want to go a step further, you can even add a new panel and removing the old one.

**Comment by severusseptimius** [comment]
Also, what WM are you using?

**Comment by lidgnulinux** [comment]
> Does this happen when you set the icon as Circle?

All options give same that strange behavior.

**Comment by lidgnulinux** [comment]
> Also, what WM are you using?

Openbox.

**Comment by lidgnulinux** [comment]
It seems that systray is messed up. All icon trays are misplaced.

**Comment by lidgnulinux** [comment]
> Can you remove the config files from`~/.config/lxqt` (`panel.conf`,`lxqt-powermanagement.conf` and `power.conf`), and log out and in again? This should reset the panel back to default

Woah, those do the trick. Tray is usable now. Thanks. Closing it now.

**Comment by severusseptimius** [comment]
Great! I'm glad it worked.

**Comment by lidgnulinux** [comment]
> Great! I'm glad it worked.

Thanks sir for bringing these packages.
