### ISSUE TITLE
Firefox snap is not updated

### ISSUE THREAD

**Issue by ralf3u** [severusseptimius/lxqt-1.1-debian#7]
it seems to be that Firefox snap is not updated, although I do updates with `sudo apt update` and `sudo apt dist-upgrade` on Lubuntu 22.04; every day there is a message on the screen counting down the days:

![firefox_snap](https://user-images.githubusercontent.com/68117017/173546519-e25a2df4-8043-4c12-82f7-b5a0fdb46726.jpg)

**Comment by severusseptimius** [comment]
Again, this has no relation to this repo. You should file a bug report to ubuntu.
