### ISSUE TITLE
Debian 12 breaks dependences of Lxqt only

### ISSUE THREAD

**Issue by Attigliuzzo** [severusseptimius/lxqt-1.1-debian#8]
Tonight i was upgrading my os but it is trying to remove the whole Lxqt DE:

`I seguenti pacchetti saranno RIMOSSI:
  libfm-qt11 liblxqt1 libqt5xdg3 libqt5xdgiconloader3
  lximage-qt lxqt-about lxqt-admin lxqt-archiver
  lxqt-config lxqt-globalkeys lxqt-notificationd
  lxqt-openssh-askpass lxqt-panel lxqt-policykit
  lxqt-powermanagement lxqt-qtplugin lxqt-runner
  lxqt-session lxqt-sudo pcmanfm-qt qps qtxdg-dev-tools
  screengrab xdg-desktop-portal-lxqt`

`I seguenti pacchetti saranno aggiornati:
  libpyside2-py3-5.15 libqt5core5a libqt5dbus5
  libqt5designer5 libqt5gui5 libqt5network5
  libqt5opengl5 libqt5positioning5 libqt5printsupport5
  libqt5qml5 libqt5qmlmodels5 libqt5quick5
  libqt5sensors5 libqt5sql5 libqt5sql5-sqlite
  libqt5svg5 libqt5test5 libqt5webchannel5
  libqt5webkit5 libqt5widgets5 libqt5x11extras5
  libqt5xml5 libqt5xmlpatterns5 python3-pyqt5
  qt5-gtk-platformtheme qt5-image-formats-plugins
26 aggiornati, 0 installati, 24 da rimuovere e 0 non aggiornati.
`

Qt5 libraries are upgraded from 5.12 to 5.14:

![ass](https://user-images.githubusercontent.com/42100711/175145186-44d5ef26-f707-44eb-89fb-b5a691dada11.jpeg)

**Comment by Attigliuzzo** [comment]
I did a test, i upgraded all packages and let my system remove lxqt. After that i thought to reinstall manually Lxqt 1.1. This is the output, the package qtbase-abi-5-15-2 is missing and it is required by libfm-qt11. I cannot find anywhere:

`Selezionato il pacchetto libfm-qt11:amd64 non precedentemente selezionato.
(Lettura del database... 158503 file e directory attualmente installati.)
Preparativi per estrarre libfm-qt11_1.1.0-1_amd64.deb...
Estrazione di libfm-qt11:amd64 (1.1.0-1)...
Preparativi per estrarre libfm-qt-l10n_1.1.0-1_all.deb...
Estrazione di libfm-qt-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto liblxqt1 non precedentemente selezionato.
Preparativi per estrarre liblxqt1_1.1.0-1_amd64.deb...
Estrazione di liblxqt1 (1.1.0-1)...
Preparativi per estrarre liblxqt-globalkeys1_1.1.0-1_amd64.deb...
Estrazione di liblxqt-globalkeys1:amd64 (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre liblxqt-globalkeys-ui1_1.1.0-1_amd64.deb...
Estrazione di liblxqt-globalkeys-ui1:amd64 (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre liblxqt-l10n_1.1.0-1_all.deb...
Estrazione di liblxqt-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto libqt5xdg3:amd64 non precedentemente selezionato.
Preparativi per estrarre libqt5xdg3_3.9.1-0_amd64.deb...
Estrazione di libqt5xdg3:amd64 (3.9.1-0)...
Selezionato il pacchetto libqt5xdgiconloader3:amd64 non precedentemente selezionato.
Preparativi per estrarre libqt5xdgiconloader3_3.9.1-0_amd64.deb...
Estrazione di libqt5xdgiconloader3:amd64 (3.9.1-0)...
Preparativi per estrarre libqtermwidget5-1_1.1.0-1_amd64.deb...
Estrazione di libqtermwidget5-1:amd64 (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto libqtermwidget5-1-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre libqtermwidget5-1-dev_1.1.0-1_amd64.deb...
Estrazione di libqtermwidget5-1-dev:amd64 (1.1.0-1)...
Preparativi per estrarre libsysstat-qt5-0_0.4.6-1_amd64.deb...
Estrazione di libsysstat-qt5-0:amd64 (0.4.6-1) su (0.4.6-1)...
Selezionato il pacchetto lximage-qt non precedentemente selezionato.
Preparativi per estrarre lximage-qt_1.1.0-1_amd64.deb...
Estrazione di lximage-qt (1.1.0-1)...
Preparativi per estrarre lximage-qt-l10n_1.1.0-1_all.deb...
Estrazione di lximage-qt-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-about non precedentemente selezionato.
Preparativi per estrarre lxqt-about_1.1.0-1_amd64.deb...
Estrazione di lxqt-about (1.1.0-1)...
Preparativi per estrarre lxqt-about-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-about-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-admin non precedentemente selezionato.
Preparativi per estrarre lxqt-admin_1.1.0-1_amd64.deb...
Estrazione di lxqt-admin (1.1.0-1)...
Preparativi per estrarre lxqt-admin-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-admin-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-archiver non precedentemente selezionato.
Preparativi per estrarre lxqt-archiver_0.6.0-1_amd64.deb...
Estrazione di lxqt-archiver (0.6.0-1)...
Preparativi per estrarre lxqt-archiver-l10n_0.6.0-1_all.deb...
Estrazione di lxqt-archiver-l10n (0.6.0-1) su (0.6.0-1)...
Selezionato il pacchetto lxqt-config non precedentemente selezionato.
Preparativi per estrarre lxqt-config_1.1.0-1_amd64.deb...
Estrazione di lxqt-config (1.1.0-1)...
Preparativi per estrarre lxqt-config-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-config-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-globalkeys non precedentemente selezionato.
Preparativi per estrarre lxqt-globalkeys_1.1.0-1_amd64.deb...
Estrazione di lxqt-globalkeys (1.1.0-1)...
Preparativi per estrarre lxqt-globalkeys-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-globalkeys-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-notificationd non precedentemente selezionato.
Preparativi per estrarre lxqt-notificationd_1.1.0-1_amd64.deb...
Estrazione di lxqt-notificationd (1.1.0-1)...
Preparativi per estrarre lxqt-notificationd-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-notificationd-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-openssh-askpass non precedentemente selezionato.
Preparativi per estrarre lxqt-openssh-askpass_1.1.0-1_amd64.deb...
Estrazione di lxqt-openssh-askpass (1.1.0-1)...
Preparativi per estrarre lxqt-openssh-askpass-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-openssh-askpass-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-panel non precedentemente selezionato.
Preparativi per estrarre lxqt-panel_1.1.0-1_amd64.deb...
Estrazione di lxqt-panel (1.1.0-1)...
Preparativi per estrarre lxqt-panel-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-panel-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-policykit non precedentemente selezionato.
Preparativi per estrarre lxqt-policykit_1.1.0-1_amd64.deb...
Estrazione di lxqt-policykit (1.1.0-1)...
Preparativi per estrarre lxqt-policykit-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-policykit-l10n (1.1.0-1) su (0.16.0-1)...
Selezionato il pacchetto lxqt-powermanagement non precedentemente selezionato.
Preparativi per estrarre lxqt-powermanagement_1.1.0-1_amd64.deb...
Estrazione di lxqt-powermanagement (1.1.0-1)...
Preparativi per estrarre lxqt-powermanagement-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-powermanagement-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-qtplugin:amd64 non precedentemente selezionato.
Preparativi per estrarre lxqt-qtplugin_1.1.0-1_amd64.deb...
Estrazione di lxqt-qtplugin:amd64 (1.1.0-1)...
Selezionato il pacchetto lxqt-runner non precedentemente selezionato.
Preparativi per estrarre lxqt-runner_1.1.0-1_amd64.deb...
Estrazione di lxqt-runner (1.1.0-1)...
Preparativi per estrarre lxqt-runner-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-runner-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto lxqt-session non precedentemente selezionato.
Preparativi per estrarre lxqt-session_1.1.1-1_amd64.deb...
Estrazione di lxqt-session (1.1.1-1)...
Preparativi per estrarre lxqt-session-l10n_1.1.1-1_all.deb...
Estrazione di lxqt-session-l10n (1.1.1-1) su (1.1.1-1)...
Selezionato il pacchetto lxqt-sudo non precedentemente selezionato.
Preparativi per estrarre lxqt-sudo_1.1.0-1_amd64.deb...
Estrazione di lxqt-sudo (1.1.0-1)...
Preparativi per estrarre lxqt-sudo-l10n_1.1.0-1_all.deb...
Estrazione di lxqt-sudo-l10n (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre lxqt-system-theme_1.1.0-1_all.deb...
Estrazione di lxqt-system-theme (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre lxqt-themes_1.1.0-1_all.deb...
Estrazione di lxqt-themes (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre pavucontrol-qt_1.1.0-1_amd64.deb...
Estrazione di pavucontrol-qt (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre pavucontrol-qt-l10n_1.1.0-1_all.deb...
Estrazione di pavucontrol-qt-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto pcmanfm-qt non precedentemente selezionato.
Preparativi per estrarre pcmanfm-qt_1.1.0-1_amd64.deb...
Estrazione di pcmanfm-qt (1.1.0-1)...
Preparativi per estrarre pcmanfm-qt-l10n_1.1.0-1_all.deb...
Estrazione di pcmanfm-qt-l10n (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto qps non precedentemente selezionato.
Preparativi per estrarre qps_2.5.0-1_amd64.deb...
Estrazione di qps (2.5.0-1)...
Preparativi per estrarre qterminal_1.1.0-1_amd64.deb...
Estrazione di qterminal (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre qterminal-l10n_1.1.0-1_all.deb...
Estrazione di qterminal-l10n (1.1.0-1) su (1.1.0-1)...
Preparativi per estrarre qtermwidget5-data_1.1.0-1_all.deb...
Estrazione di qtermwidget5-data (1.1.0-1) su (1.1.0-1)...
Selezionato il pacchetto qtxdg-dev-tools non precedentemente selezionato.
Preparativi per estrarre qtxdg-dev-tools_3.9.1-0_amd64.deb...
Estrazione di qtxdg-dev-tools (3.9.1-0)...
Selezionato il pacchetto screengrab non precedentemente selezionato.
Preparativi per estrarre screengrab_2.4.0-1_amd64.deb...
Estrazione di screengrab (2.4.0-1)...
Selezionato il pacchetto xdg-desktop-portal-lxqt non precedentemente selezionato.
Preparativi per estrarre xdg-desktop-portal-lxqt_0.2.0-1_amd64.deb...
Estrazione di xdg-desktop-portal-lxqt (0.2.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di libfm-qt11:amd64:
 libfm-qt11:amd64 dipende da qtbase-abi-5-15-2; tuttavia:
  Il pacchetto qtbase-abi-5-15-2 non è installato.

dpkg: errore nell'elaborare il pacchetto libfm-qt11:amd64 (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di libfm-qt-l10n (1.1.0-1)...
Configurazione di liblxqt-globalkeys1:amd64 (1.1.0-1)...
Configurazione di liblxqt-globalkeys-ui1:amd64 (1.1.0-1)...
Configurazione di liblxqt-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di libqt5xdg3:amd64:
 libqt5xdg3:amd64 dipende da qtbase-abi-5-15-2; tuttavia:
  Il pacchetto qtbase-abi-5-15-2 non è installato.

dpkg: errore nell'elaborare il pacchetto libqt5xdg3:amd64 (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di libqt5xdgiconloader3:amd64:
 libqt5xdgiconloader3:amd64 dipende da libqt5xdg3 (>= 3.9.1); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.
 libqt5xdgiconloader3:amd64 dipende da qtbase-abi-5-15-2; tuttavia:
  Il pacchetto qtbase-abi-5-15-2 non è installato.

dpkg: errore nell'elaborare il pacchetto libqt5xdgiconloader3:amd64 (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di libsysstat-qt5-0:amd64 (0.4.6-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lximage-qt:
 lximage-qt dipende da libfm-qt11 (>= 1.1.0); tuttavia:
  Il pacchetto libfm-qt11:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lximage-qt (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lximage-qt-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-about:
 lxqt-about dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-about (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-about-l10n (1.1.0-1)...
Configurazione di lxqt-admin-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-archiver:
 lxqt-archiver dipende da libfm-qt11 (>= 1.1.0); tuttavia:
  Il pacchetto libfm-qt11:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-archiver (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-archiver-l10n (0.6.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-config:
 lxqt-config dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-config (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-config-l10n (1.1.0-1)...
Configurazione di lxqt-globalkeys-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-notificationd:
 lxqt-notificationd dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-notificationd (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-notificationd-l10n (1.1.0-1)...
Configurazione di lxqt-openssh-askpass-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-panel:
 lxqt-panel dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-panel (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-panel-l10n (1.1.0-1)...
Configurazione di lxqt-policykit-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-powermanagement:
 lxqt-powermanagement dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-powermanagement (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-powermanagement-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-qtplugin:amd64:
 lxqt-qtplugin:amd64 dipende da libqt5xdgiconloader3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdgiconloader3:amd64 non è ancora configurato.
 lxqt-qtplugin:amd64 dipende da qtbase-abi-5-15-2; tuttavia:
  Il pacchetto qtbase-abi-5-15-2 non è installato.
 lxqt-qtplugin:amd64 dipende da libfm-qt11; tuttavia:
  Il pacchetto libfm-qt11:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-qtplugin:amd64 (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-runner:
 lxqt-runner dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-runner (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-runner-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-session:
 lxqt-session dipende da libqt5xdg3 (>= 3.9.1); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.
 lxqt-session dipende da lxqt-qtplugin; tuttavia:
  Il pacchetto lxqt-qtplugin:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-session (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di lxqt-session-l10n (1.1.1-1)...
Configurazione di lxqt-sudo-l10n (1.1.0-1)...
Configurazione di lxqt-system-theme (1.1.0-1)...
Configurazione di lxqt-themes (1.1.0-1)...
Configurazione di pavucontrol-qt (1.1.0-1)...
Configurazione di pavucontrol-qt-l10n (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di pcmanfm-qt:
 pcmanfm-qt dipende da libfm-qt11 (>= 1.1.0); tuttavia:
  Il pacchetto libfm-qt11:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto pcmanfm-qt (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di pcmanfm-qt-l10n (1.1.0-1)...
Configurazione di qterminal-l10n (1.1.0-1)...
Configurazione di qtermwidget5-data (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di qtxdg-dev-tools:
 qtxdg-dev-tools dipende da libqt5xdg3 (= 3.9.1-0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.
 qtxdg-dev-tools dipende da libqt5xdgiconloader3 (= 3.9.1-0); tuttavia:
  Il pacchetto libqt5xdgiconloader3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto qtxdg-dev-tools (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di screengrab:
 screengrab dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto screengrab (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di xdg-desktop-portal-lxqt:
 xdg-desktop-portal-lxqt dipende da libfm-qt11 (>= 1.1.0); tuttavia:
  Il pacchetto libfm-qt11:amd64 non è ancora configurato.
 xdg-desktop-portal-lxqt dipende da qtbase-abi-5-15-2; tuttavia:
  Il pacchetto qtbase-abi-5-15-2 non è installato.

dpkg: errore nell'elaborare il pacchetto xdg-desktop-portal-lxqt (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di liblxqt1:
 liblxqt1 dipende da libqt5xdg3 (>= 3.9.0); tuttavia:
  Il pacchetto libqt5xdg3:amd64 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto liblxqt1 (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di libqtermwidget5-1:amd64 (1.1.0-1)...
Configurazione di libqtermwidget5-1-dev:amd64 (1.1.0-1)...
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-admin:
 lxqt-admin dipende da liblxqt1 (>= 1.0.0); tuttavia:
  Il pacchetto liblxqt1 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-admin (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-globalkeys:
 lxqt-globalkeys dipende da liblxqt1 (>= 1.0.0); tuttavia:
  Il pacchetto liblxqt1 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-globalkeys (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-openssh-askpass:
 lxqt-openssh-askpass dipende da liblxqt1 (>= 1.0.0); tuttavia:
  Il pacchetto liblxqt1 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-openssh-askpass (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-policykit:
 lxqt-policykit dipende da liblxqt1 (>= 1.0.0); tuttavia:
  Il pacchetto liblxqt1 non è ancora configurato.
 lxqt-policykit dipende da lxqt-session; tuttavia:
  Il pacchetto lxqt-session non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-policykit (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di lxqt-sudo:
 lxqt-sudo dipende da liblxqt1 (>= 1.0.0); tuttavia:
  Il pacchetto liblxqt1 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto lxqt-sudo (--install):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di qps:
 qps dipende da liblxqt1 (>= 1.0.0); tuttavia:
  Il pacchetto liblxqt1 non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto qps (--install):
 problemi con le dipendenze - lasciato non configurato
Configurazione di qterminal (1.1.0-1)...
Elaborazione dei trigger per libc-bin (2.33-7)...
Elaborazione dei trigger per shared-mime-info (2.2-1)...
Elaborazione dei trigger per mailcap (3.70+nmu1)...
Elaborazione dei trigger per desktop-file-utils (0.26-1)...
Elaborazione dei trigger per hicolor-icon-theme (0.17-2)...
Elaborazione dei trigger per man-db (2.10.2-1)...
Si sono verificati degli errori nell'elaborazione:
 libfm-qt11:amd64
 libqt5xdg3:amd64
 libqt5xdgiconloader3:amd64
 lximage-qt
 lxqt-about
 lxqt-archiver
 lxqt-config
 lxqt-notificationd
 lxqt-panel
 lxqt-powermanagement
 lxqt-qtplugin:amd64
 lxqt-runner
 lxqt-session
 pcmanfm-qt
 qtxdg-dev-tools
 screengrab
 xdg-desktop-portal-lxqt
 liblxqt1
 lxqt-admin
 lxqt-globalkeys
 lxqt-openssh-askpass
 lxqt-policykit
 lxqt-sudo
 qps
`
@severusseptimius , the libfm-qt11 package requires the qtbase-abi-5-12-2 package, that package isn't available neither in Ubuntu, it's been replaced by libqt5core5a. Could you upload it or remove that dependency?
Thanks

**Comment by foldfree** [comment]
I am also running debian bookworm, and also have issues with qt related packages. But not exactly the same as Attigliuzzo

apt is not updating the following packages:

`The following packages have been kept back:
  fcitx5-frontend-qt5 kwayland-integration libfcitx5-qt1 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5 libqt5opengl5
  libqt5opengl5-dev libqt5printsupport5 libqt5qml5 libqt5qmlmodels5 libqt5qmlworkerscript5 libqt5quick5-gles libqt5sql5 libqt5sql5-sqlite libqt5svg5
  libqt5test5 libqt5waylandclient5 libqt5waylandcompositor5 libqt5widgets5 libqt5x11extras5 libqt5xml5 libvkd3d1 libvkd3d1:i386 qml-module-qtquick2
  qt5-gtk-platformtheme qt5-gtk2-platformtheme qt5-image-formats-plugins qt5-qmake qt5-qmake-bin qt5-style-plugin-cleanlooks qt5-style-plugin-motif
  qt5-style-plugin-plastique qt5-style-plugins qt5ct qtbase5-dev qtbase5-dev-tools qtwayland5`

**Comment by stefonarch** [comment]
Same here, more or less (fcitx not installed e.g).

**Comment by severusseptimius** [comment]
Hi! Sorry for the delay. I had a hard drive failure and for the past few days I tried to recover as many files as I could. Backups seem so unimportant until you need them...

Any way, back on topic, I have updated the packages and they *should* be ok now. #5 should also be fixed with the latest commit.

**Comment by Attigliuzzo** [comment]
All solved!! thanks for your efforts to compile this fabulous light DE.

**Comment by stefonarch** [comment]
> Anyway, back on topic, I have updated the packages and they _should_ be ok now. #5 should also be fixed with the latest commit.

They _are_ ok - thanks a lot!

**Comment by stefonarch** [comment]
PS: I found this and it looks working fine:
https://linoxide.com/how-to-create-your-own-repository-for-packages-on-debian/
