### ISSUE TITLE
in Firefox the add-on spelling works only with the system language, but not for other languages

### ISSUE THREAD

**Issue by ralf3u** [severusseptimius/lxqt-1.1-debian#9]
see title of this issue

**Comment by stefonarch** [comment]
Again - this is not related in any means with this repository or lxqt.

**Comment by stefonarch** [comment]
You just make confusion, because spellchecking in firefox and debian works fine for many languages.
![schermata-23 giu 16:00-03](https://user-images.githubusercontent.com/10681413/175318162-dd1e275a-9625-4335-b602-a144c2cd9c93.png)

**Comment by severusseptimius** [comment]
@stefonarch is right. This has absolutley nothing to do with this repo.
